### ISSUE TITLE
Consistent Block Colors

### ISSUE THREAD

**Issue by chrisconcord** [musicarroll/tetris#3]
Make each type of block have a consistent and fixed color.  Colors of block should not change at random as they do now.

**Comment by musicarroll** [comment]
Make your issue titles shorter and don't forget to add a thorough description.

**Comment by musicarroll** [comment]
Had a bug in which the first block color was incorrect.  It turned out that there were still two places where random.choice() was being called.    It is not fixed.

**Comment by musicarroll** [comment]
Fixed.
